config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ''
  end

  scope "(:locale)", locale: /en|vi/ do 
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
  end
  
  namespace :admin do
    root "users#index"
    resources :users, concerns: :paginatable
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/layouts_admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mt-">
  <%= link_to "My Blog", "#", class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" 
    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mt-2 ml-auto">
      <!-- Language -->
      <div class="dropdown mr-5">
        <button class="btn btn-outline-secondary dropdown-toggle" type="button"
          id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <%= t(".language") %>
        </button>
        <div class="dropdown-menu" aria-laelledby="dropdownMenuButton">
          <li>
            <%= link_to t(".vietnamese"), locale:"vi", class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to t(".english"), locale:"en", class: "dropdown-item" %>
          </li>
        </div>
      </div>
      <li class="nav-item mr-3">
        <%= link_to t(".home"), root_path, class: "nav-link" %>
      </li>
      <% if !logged_in? %>
        <li class="nav-item mr-3">
          <%= link_to t(".signup"), signup_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".signin"), login_path, class: "nav-link" %>
        </li>
      <% else %>
        <% if current_user.admin? %>
        <li class="nav-item mr-3">
          <%= link_to t(".user"), admin_root_path, class: "nav-link" %>
        </li>
        <li>    
          <div class="dropdown">
            <button class="btn btn-outline-secondary dropdown-toggle" 
              type="button" id="dropdownMenuButton" data-toggle="dropdown" 
              aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </button> 
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to t(".admin_path"), admin_root_path, 
                class: "dropdown-item" %>
              <%= link_to t(".profile"), admin_user_path(current_user), 
                class: "dropdown-item" %>
              <%= link_to t(".setting"), edit_admin_user_path(current_user), 
                class: "dropdown-item" %>
              <%= link_to t(".log_out"), logout_path, class: "dropdown-item",
                method: :delete %>
            </div>           
          </div>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</nav>