config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ''
  end

  scope "(:locale)", locale: /en|vi/ do 
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
  end
  
  namespace :admin do
    root "users#index"
    resources :users, concerns: :paginatable
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save :downcase_email

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    # Returns the hash digest of the given string
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns the hash digest of the given string
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a users in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  private
    # Converts email to all lower-case
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:create, :destroy]

  def index
    @users = User.all.page(params[:page]).per(10) 
  end
  
  def show
    @user = User.find params[:id]
  end

  def new 
    @user = User.new
  end

  def create 
    @user = User.new user_params
    if @user.save 
      flash[:success] = t(".welcome")
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = t(".profile_updated")
      redirect_to admin_user_path
    else
      render :edit 
    end
  end
  
  def destroy
    @user = User.find_by id: params[:id]
    @user.destroy
    flash[:success] = t(".user_deleted")
    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit :name, :email, :password, 
        :password_confirmation
    end

    # Before fillers

    # Confirms a admin user
    def admin_user 
      redirect_to(root_url) unless current_user.admin?
    end

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        flash[:danger] = t(".please_log_in")
        redirect_to login_url
      end
    end

    # Correct_user
    def correct_user
      @user = User.find params[:id]
      redirect_to root_url unless current_user?(@user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new 
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user 
      flash[:success] = t(".welcome")
      redirect_to @user
    else
      render :new
    end
  end
 
  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = t(".profile_updated")
      redirect_to @user
    else
      render :edit 
    end
  end

  private 
    def user_params
      params.require(:user).permit :name, :email, :password, 
        :password_confirmation
    end

    # Before filters

    # Confirms a logged-in users
    def logged_in_user
      unless logged_in?
        flash[:danger] = t(".please_log_in")
        redirect_to login_url
      end
    end

    # Correct user
    def correct_user
      @user = User.find params[:id]
      redirect_to root_url unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/edit.html.erb
<% provide :title, t(".edit_user") %>
<h1><%= t(".update_your_profile") %></h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_for [:admin, @user] do |f| %>
      <%= render "admin/shared/error_messages" %>
      <div class="field">
        <%= f.label :name, t(".name"), class: "text-info" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="field mt-3">
        <%= f.label :email, t(".email"), class: "text-info" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="field mt-3">
        <%= f.label :password, t(".new_password"), class: "text-info" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="field mt-3">
        <%= f.label :password_confirmation, t(".confirmation"), 
          class: "text-info" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="field mt-3">
        <%= f.submit t(".update"), 
          class: "btn btn-outline-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t(".all_users") %>
<div class="row mt-3">
  <div class="button-create-user mb-3">
    <%= link_to t(".create_new_user"), new_admin_user_path, 
      class: "btn btn-outline-success" %>
  </div>
  
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><%= t(".name") %></th>
        <th scope="col"><%= t(".email") %></th>
        <th scope="col"><%= t(".delete") %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do  |user, i| %>
      <tr>
        <th scope="row"> <%= i + 1 %></th>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><% if current_user.admin? && !current_user?(user) %> 
              <%= link_to t(".delete"), admin_user_path(user.id),
              method: :delete, data: { confirm: t(".are_you_sure") } %>
            <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="field">
   <%=  paginate @users, theme: "twitter-bootstrap-4",
    pagination_class: "pagination-sm", nav_class: "d-inline-b" %>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide :title, t(".sign_up") %>
<h1 class="text-center"><%= t(".sign_up") %></h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_for [:admin, @user] do |f| %>
      <%= render "admin/shared/error_messages" %>
      <div class="field">
        <%= f.label :name, t(".name"), class: "text-info"%>
        <%= f.text_field :name, placeholder: t(".name"), class: "form-control"%>
      </div>
     
      <div class="field mt-3">
        <%= f.label :email, t(".email"), class: "text-info mt-2" %>
        <%= f.email_field :email, placeholder: t(".email"), 
          class: "form-control" %>
      </div>

      <div class="field mt-3">
         <%= f.label :password, t(".password"), class: "text-info mt-2" %>
        <%= f.password_field :password, placeholder: t(".password"), 
          class: "form-control" %>
      </div>
      <div class="field mt-3">
        <%= f.label :password_confirmation, t(".confirmation"), 
          class: "text-info mt-2" %>
        <%= f.password_field :password_confirmation, 
          placeholder: t(".confirmation"), class: "form-control" %>
      </div>
      <div class="field mt-3">
        <%= f.submit  t(".create_my_account"), 
        class: "btn btn-outline-primary mt-3 form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<%= provide :title,  @user.name %>
<div class="row mt-3">
  <div class="col-md-6">
    <h5>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h5>
  </div>
</div>